# Generated by Django 4.1.5 on 2023-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_stam'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='media/home_images')),
            ],
            options={
                'verbose_name_plural': 'Home Images',
            },
        ),
    ]
