# Generated by Django 4.1.5 on 2023-01-24 22:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('instegram', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('img', models.ImageField(upload_to='media/about_images')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
