# Generated by Django 4.1.5 on 2023-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='instegram_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
