# Generated by Django 4.1.5 on 2023-01-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=55)),
                ('img', models.ImageField(upload_to='media/reviews')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
