# Generated by Django 4.1.5 on 2023-01-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reviews_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
    ]
