# Generated by Django 4.1.5 on 2023-01-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categoryimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
